version: '3.8'

volumes:
    logs:
        driver: local

services:
    web:
        image: library/nginx:1.18.0
        ports:
            - "9000:80"
        volumes:
            - ./infra/docker/web/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/app
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: infra/docker/app/Dockerfile
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LANG: "ja_JP.UTF-8"
            LC_ALL: "ja_JP.UTF-8"
        volumes:
            - .:/var/www/app
            - logs:/var/www/logs
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: mutter_db
            MYSQL_PASSWORD: mutter_password
            MYSQL_ROOT_PASSWORD: mutter_admin_password
        ports:
            - "3306:3306"
        volumes:
            - ./infra/docker/db/my.conf:/etc/mysql/conf.d/my.conf
            - ./infra/docker/db/persistence/:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-use-native-aio=0 --sql_mode="STRICT_TRANS_TABLES"
